# Generated by Django 2.1.7 on 2019-05-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190516_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='{{ post.author }}/images'),
        ),
    ]
