# Generated by Django 2.1.7 on 2019-05-16 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
