# Generated by Django 2.1.7 on 2019-05-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190516_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='post_images'),
        ),
    ]
